name: Build and Push Docker when Release

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.release.target_commitish }}

      - name: Set release tag
        run: |
          echo "RELEASE_TAG=${{ github.event.release.tag_name }}" >> ${GITHUB_ENV}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.MY_TOKEN }}

      - name: Owner names
        run: |
          GITOWNER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')
          echo "GITOWNER=$GITOWNER" >> ${GITHUB_ENV}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ env.GITOWNER }}/allwinschatgpt:latest
            ghcr.io/${{ env.GITOWNER }}/allwinschatgpt:${{ env.RELEASE_TAG }}
            ${{ secrets.DOCKERHUB_USERNAME }}/allwinschatgpt:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/allwinschatgpt:${{ env.RELEASE_TAG }}
